---
- name: Create directory for apt keyrings
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: yes

- name: Add Docker official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/keyrings/docker.gpg
    state: present
  become: yes

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch={{ ansible_architecture | replace('x86_64','amd64') }}
      signed-by=/etc/apt/keyrings/docker.gpg]
      https://download.docker.com/linux/ubuntu
      jammy stable
    state: present
    filename: docker
  become: yes

- name: Update apt cache after adding Docker repo
  ansible.builtin.apt:
    update_cache: yes
  become: yes

- name: Install Docker Engine, CLI, Containerd, and Docker Compose plugin
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin # Installs compose as `docker compose` command
    state: present
  become: yes

- name: Ensure Docker service is started and enabled on boot
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: Add executing user to docker group for non-sudo docker commands
  ansible.builtin.user:
    name: "{{ ansible_user }}" # The user running the playbook via SSH
    groups: docker
    append: yes
  become: yes
  notify: Warn user about group membership # Defined in main playbook.yml handlers
